title: Phenopackets-JS
description: JavaScript library for GA4GH Phenopackets
theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Enable relative links
relative_links:
  enabled: true
  collections: true
